### PR TITLE
Updates for scripts 1 and 2

### PR DESCRIPTION
**Pull request by mrbodean**
Added error checking and moved some functions from the script to a functions script to reduce some of the code duplication. Added -verbose option and appending to log files. 
Accept or reject, I am just sharing.

### CODE REVIEW

**Comment by jaromirk** [comment]
Really cool! Ill take a look more in depth as ill get to pc. Thx!

**Comment by jaromirk** [comment]
I reviewed it, cool! Can you send more functions to functions.ps1? Also from 3_deploy? I'll test it next week and most probably merge it. This is really what I needed as I'm new to scripting..

**Comment by mrbodean** [comment]
Sure, Glad to help out. This really helps me rebuild my labs for experimentation.

**Comment by jaromirk** [comment]
I plan change in deploy to support better win 2012 r2 clusters (specify multiple shared disks), so function would really help.

**Comment by MS-MatthewWalker** [comment]
you can review https://github.com/PlagueHO/LabBuilder for ideas on functions

**Comment by MS-MatthewWalker** [comment]
Also do you want to do more work or go ahead and commit the changes?

**Comment by jaromirk** [comment]
Hey all, I tested it and it crashes when running scripts is disabled on system (defaults). Ill hold merge and will take a look deeper and with Matt we will work on merging the ideas (I like separate functions.ps1, I'd like to discuss write-output as it does not produce color output, not sure if we want additional file - I like solutions as simple as possible and there are just few duplicates (one answer file and elevation ... Can you take a look into how to rewrite creating vm in 3_deploy) thx!

**Comment by jaromirk** [comment]
Hi! I just ran thru the changes. I keep functions in the scripts and I kept write-host instead of write-output (or error/info) as this is interactive script and I want to show colored output. I grabbed some ideas. THX!

**Pull request closed without merging**
